import { PropertyFeedItem } from '../../types/database';

export const MOCK_PROPERTIES: PropertyFeedItem[] = [
  {
    id: 'mock-1',
    owner_id: 'agent-1',
    deal_type: 'sale',
    listing_type: 'official',
    property_type: 'Apartment',
    price: 2_850_000,
    price_currency: 'AED',
    price_period: null,
    bedrooms: 3,
    bathrooms: 2,
    area_sqft: 1850,
    location_name: 'Marina Promenade',
    community_name: 'Dubai Marina',
    description: 'Просторная квартира с видом на marina.',
    furnished: 'yes',
    handover: 'ready',
    is_distress: false,
    photos: ['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=80'],
    published_at: '2026-06-07T10:00:00Z',
    owner_full_name: 'Алексей Петров',
    owner_photo_url: null,
    owner_agency_name: 'Emirates Elite Properties',
    is_network: false,
    developer_name: null,
  },
  {
    id: 'mock-2',
    owner_id: 'agent-2',
    deal_type: 'sale',
    listing_type: 'pocket',
    property_type: 'Townhouse',
    price: 4_200_000,
    price_currency: 'AED',
    price_period: null,
    bedrooms: 4,
    bathrooms: 3,
    area_sqft: 2700,
    location_name: 'Frond G',
    community_name: 'Palm Jumeirah',
    description: 'Эксклюзивный таунхаус на Пальме.',
    furnished: 'yes',
    handover: 'ready',
    is_distress: false,
    photos: ['https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80'],
    published_at: '2026-06-08T09:00:00Z',
    owner_full_name: 'Мария Соколова',
    owner_photo_url: null,
    owner_agency_name: 'Luxury Homes Dubai',
    is_network: true,
    developer_name: null,
  },
  {
    id: 'mock-3',
    owner_id: 'agent-3',
    deal_type: 'sale',
    listing_type: 'official',
    property_type: 'Studio',
    price: 1_450_000,
    price_currency: 'AED',
    price_period: null,
    bedrooms: 0,
    bathrooms: 1,
    area_sqft: 750,
    location_name: 'Canal View',
    community_name: 'Business Bay',
    description: 'Студия с захватывающим видом на Canal.',
    furnished: 'yes',
    handover: 'ready',
    is_distress: true,
    photos: ['https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80'],
    published_at: '2026-06-09T07:30:00Z',
    owner_full_name: 'Дмитрий Козлов',
    owner_photo_url: null,
    owner_agency_name: 'Bay View Realty',
    is_network: false,
    developer_name: null,
  },
  {
    id: 'mock-4',
    owner_id: 'agent-4',
    deal_type: 'rent',
    listing_type: 'official',
    property_type: 'Apartment',
    price: 85_000,
    price_currency: 'AED',
    price_period: 'yr',
    bedrooms: 2,
    bathrooms: 2,
    area_sqft: 1200,
    location_name: 'The Walk',
    community_name: 'JBR',
    description: 'Квартира в 2 минутах от пляжа JBR.',
    furnished: 'yes',
    handover: 'ready',
    is_distress: false,
    photos: ['https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80'],
    published_at: '2026-06-06T14:00:00Z',
    owner_full_name: 'Анна Белова',
    owner_photo_url: null,
    owner_agency_name: 'Beachfront Agency',
    is_network: true,
    developer_name: null,
  },
  {
    id: 'mock-5',
    owner_id: 'agent-5',
    deal_type: 'sale',
    listing_type: 'official',
    property_type: 'Villa',
    price: 6_800_000,
    price_currency: 'AED',
    price_period: null,
    bedrooms: 5,
    bathrooms: 5,
    area_sqft: 5200,
    location_name: 'Sector E',
    community_name: 'Emirates Hills',
    description: 'Вилла с видом на гольф-поле.',
    furnished: 'no',
    handover: 'ready',
    is_distress: false,
    photos: ['https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800&q=80'],
    published_at: '2026-06-05T11:00:00Z',
    owner_full_name: 'Сергей Иванов',
    owner_photo_url: null,
    owner_agency_name: 'Hills Premium Real Estate',
    is_network: false,
    developer_name: 'Emaar',
  },
];
